import { IngredientCategory, StorageType } from "@prisma/client";

export type SeedIngredient = { id:string; name:string; category:IngredientCategory; storageType:StorageType; shelfLifeDays:number; recommendedPurchaseLeadDays:number; isSeasonal:boolean; seasonWeeks:number[]; hasFrozenOption:boolean };
const allWeeks = Array.from({ length: 52 }, (_, i) => i + 1);
export const ingredients: SeedIngredient[] = [
{id:"pasta_secca",name:"Pasta secca",category:"pasta_rice_cereals",storageType:"pantry",shelfLifeDays:365,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"riso",name:"Riso",category:"pasta_rice_cereals",storageType:"pantry",shelfLifeDays:365,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"avena",name:"Fiocchi d'avena",category:"pasta_rice_cereals",storageType:"pantry",shelfLifeDays:240,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"pane_integrale",name:"Pane integrale",category:"bread_bakery",storageType:"pantry",shelfLifeDays:3,recommendedPurchaseLeadDays:1,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"patate",name:"Patate",category:"vegetables",storageType:"pantry",shelfLifeDays:30,recommendedPurchaseLeadDays:4,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"zucchine",name:"Zucchine",category:"vegetables",storageType:"fridge",shelfLifeDays:4,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38],hasFrozenOption:true},
{id:"pomodoro",name:"Pomodoro",category:"vegetables",storageType:"fridge",shelfLifeDays:5,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40],hasFrozenOption:true},
{id:"spinaci",name:"Spinaci",category:"vegetables",storageType:"fridge",shelfLifeDays:4,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[1,2,3,4,5,6,7,8,9,10,11,12,40,41,42,43,44,45,46,47,48,49,50,51,52],hasFrozenOption:true},
{id:"carote",name:"Carote",category:"vegetables",storageType:"fridge",shelfLifeDays:7,recommendedPurchaseLeadDays:2,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"broccoli",name:"Broccoli",category:"vegetables",storageType:"fridge",shelfLifeDays:5,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[1,2,3,4,5,6,7,8,9,10,11,12,43,44,45,46,47,48,49,50,51,52],hasFrozenOption:true},
{id:"cavolfiore",name:"Cavolfiore",category:"vegetables",storageType:"fridge",shelfLifeDays:6,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[1,2,3,4,5,6,7,8,9,10,11,12,43,44,45,46,47,48,49,50,51,52],hasFrozenOption:true},
{id:"melanzane",name:"Melanzane",category:"vegetables",storageType:"fridge",shelfLifeDays:5,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39],hasFrozenOption:true},
{id:"peperoni",name:"Peperoni",category:"vegetables",storageType:"fridge",shelfLifeDays:5,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39],hasFrozenOption:true},
{id:"insalata_lattuga",name:"Lattuga",category:"vegetables",storageType:"fridge",shelfLifeDays:3,recommendedPurchaseLeadDays:1,isSeasonal:true,seasonWeeks:[14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42],hasFrozenOption:false},
{id:"fagiolini",name:"Fagiolini",category:"vegetables",storageType:"fridge",shelfLifeDays:4,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37],hasFrozenOption:true},
{id:"zucca",name:"Zucca",category:"vegetables",storageType:"pantry",shelfLifeDays:20,recommendedPurchaseLeadDays:3,isSeasonal:true,seasonWeeks:[36,37,38,39,40,41,42,43,44,45,46,47,48,49],hasFrozenOption:true},
{id:"cipolla",name:"Cipolla",category:"vegetables",storageType:"pantry",shelfLifeDays:25,recommendedPurchaseLeadDays:5,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"aglio",name:"Aglio",category:"vegetables",storageType:"pantry",shelfLifeDays:40,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"limone",name:"Limone",category:"fruit",storageType:"fridge",shelfLifeDays:12,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[1,2,3,4,5,6,7,8,9,10,11,12,46,47,48,49,50,51,52],hasFrozenOption:false},
{id:"mela",name:"Mela",category:"fruit",storageType:"fridge",shelfLifeDays:12,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[1,2,3,4,5,6,7,8,9,10,40,41,42,43,44,45,46,47,48,49,50,51,52],hasFrozenOption:false},
{id:"pera",name:"Pera",category:"fruit",storageType:"fridge",shelfLifeDays:8,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[1,2,3,4,5,6,7,8,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52],hasFrozenOption:false},
{id:"banana",name:"Banana",category:"fruit",storageType:"pantry",shelfLifeDays:5,recommendedPurchaseLeadDays:1,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"fragole",name:"Fragole",category:"fruit",storageType:"fridge",shelfLifeDays:3,recommendedPurchaseLeadDays:1,isSeasonal:true,seasonWeeks:[14,15,16,17,18,19,20,21,22,23,24,25],hasFrozenOption:true},
{id:"arancia",name:"Arancia",category:"fruit",storageType:"fridge",shelfLifeDays:10,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[1,2,3,4,5,6,7,8,9,10,11,12,45,46,47,48,49,50,51,52],hasFrozenOption:false},
{id:"kiwi",name:"Kiwi",category:"fruit",storageType:"fridge",shelfLifeDays:10,recommendedPurchaseLeadDays:2,isSeasonal:true,seasonWeeks:[1,2,3,4,5,6,7,8,9,10,11,12,45,46,47,48,49,50,51,52],hasFrozenOption:false},
{id:"albicocca",name:"Albicocca",category:"fruit",storageType:"fridge",shelfLifeDays:4,recommendedPurchaseLeadDays:1,isSeasonal:true,seasonWeeks:[20,21,22,23,24,25,26,27,28],hasFrozenOption:false},
{id:"pesca",name:"Pesca",category:"fruit",storageType:"fridge",shelfLifeDays:4,recommendedPurchaseLeadDays:1,isSeasonal:true,seasonWeeks:[23,24,25,26,27,28,29,30,31,32,33,34,35],hasFrozenOption:false},
{id:"ceci_cotti",name:"Ceci cotti",category:"legumes",storageType:"pantry",shelfLifeDays:365,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"lenticchie_cotte",name:"Lenticchie cotte",category:"legumes",storageType:"pantry",shelfLifeDays:365,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"piselli",name:"Piselli",category:"legumes",storageType:"freezer",shelfLifeDays:240,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"petto_pollo",name:"Petto di pollo",category:"meat",storageType:"fridge",shelfLifeDays:2,recommendedPurchaseLeadDays:1,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"fesa_tacchino",name:"Fesa di tacchino",category:"meat",storageType:"fridge",shelfLifeDays:2,recommendedPurchaseLeadDays:1,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"macinato_bovino",name:"Macinato bovino",category:"meat",storageType:"fridge",shelfLifeDays:2,recommendedPurchaseLeadDays:1,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"merluzzo",name:"Filetto di merluzzo",category:"fish",storageType:"freezer",shelfLifeDays:180,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"salmone",name:"Filetto di salmone",category:"fish",storageType:"freezer",shelfLifeDays:180,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:true},
{id:"tonno_naturale",name:"Tonno al naturale",category:"fish",storageType:"pantry",shelfLifeDays:365,recommendedPurchaseLeadDays:7,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"uova",name:"Uova",category:"eggs",storageType:"fridge",shelfLifeDays:20,recommendedPurchaseLeadDays:4,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"latte",name:"Latte",category:"dairy",storageType:"fridge",shelfLifeDays:7,recommendedPurchaseLeadDays:2,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"yogurt_bianco",name:"Yogurt bianco",category:"dairy",storageType:"fridge",shelfLifeDays:14,recommendedPurchaseLeadDays:3,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"ricotta",name:"Ricotta",category:"dairy",storageType:"fridge",shelfLifeDays:5,recommendedPurchaseLeadDays:2,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"mozzarella",name:"Mozzarella",category:"dairy",storageType:"fridge",shelfLifeDays:5,recommendedPurchaseLeadDays:2,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"parmigiano",name:"Parmigiano",category:"dairy",storageType:"fridge",shelfLifeDays:30,recommendedPurchaseLeadDays:5,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"olio_evo",name:"Olio EVO",category:"condiments",storageType:"pantry",shelfLifeDays:365,recommendedPurchaseLeadDays:10,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"sale",name:"Sale",category:"condiments",storageType:"pantry",shelfLifeDays:1000,recommendedPurchaseLeadDays:20,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"basilico",name:"Basilico",category:"vegetables",storageType:"fridge",shelfLifeDays:3,recommendedPurchaseLeadDays:1,isSeasonal:true,seasonWeeks:[20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37],hasFrozenOption:true},
{id:"origano",name:"Origano",category:"condiments",storageType:"pantry",shelfLifeDays:365,recommendedPurchaseLeadDays:10,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"farina",name:"Farina",category:"pantry",storageType:"pantry",shelfLifeDays:240,recommendedPurchaseLeadDays:10,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"marmellata",name:"Marmellata",category:"pantry",storageType:"pantry",shelfLifeDays:180,recommendedPurchaseLeadDays:10,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"miele",name:"Miele",category:"pantry",storageType:"pantry",shelfLifeDays:365,recommendedPurchaseLeadDays:10,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false},
{id:"mandorle",name:"Mandorle",category:"pantry",storageType:"pantry",shelfLifeDays:180,recommendedPurchaseLeadDays:10,isSeasonal:false,seasonWeeks:allWeeks,hasFrozenOption:false}
];
