import { ActivityLevel, Goal, MealType, Person, Prisma, Sex } from "@prisma/client";

type RecipeWithIngredients = Prisma.RecipeGetPayload<{ include: { ingredients: { include: { ingredient: true } } } }>;
const activityFactors: Record<ActivityLevel, number> = { sedentary: 1.2, lightly_active: 1.375, active: 1.55, very_active: 1.725 };
const goalAdjustments: Record<Goal, number> = { maintenance: 1, light_weight_loss: 0.9, muscle_gain: 1.1, sport_energy: 1.05 };
const macroTargetPercentages: Record<Goal, { protein: number; carbs: number; fat: number }> = { maintenance: { protein: 0.2, carbs: 0.5, fat: 0.3 }, light_weight_loss: { protein: 0.25, carbs: 0.4, fat: 0.3 }, muscle_gain: { protein: 0.28, carbs: 0.45, fat: 0.27 }, sport_energy: { protein: 0.22, carbs: 0.55, fat: 0.23 } };

export function estimateDailyCalories(person: Person): number { const base=10*person.weightKg+6.25*person.heightCm-5*person.age+(person.sex===Sex.male?5:-161); const estimated=base*activityFactors[person.activityLevel]*goalAdjustments[person.goal]; return Math.max(person.age<12?900:person.age<18?1200:1400, person.age<18?estimated*0.82:estimated); }
export function estimateMacroTargets(person: Person) { const calories=estimateDailyCalories(person); const m=macroTargetPercentages[person.goal]; return { calories, proteinGrams:(calories*m.protein)/4, carbsGrams:(calories*m.carbs)/4, fatGrams:(calories*m.fat)/9 }; }
export function getPortionLabel(multiplier:number): "small" | "medium" | "large" { return multiplier<0.9?"small":multiplier>1.2?"large":"medium"; }

export function buildPortions(params:{mealType:MealType;selectedRecipes:RecipeWithIngredients[];persons:Person[];dayIndex:number;isPresentAtMeal:(personId:string, mealType:MealType, dayIndex:number)=>boolean;isSportDay:(personId:string, dayIndex:number)=>boolean;mealDistribution:Record<MealType,number>}) { const base=params.selectedRecipes.reduce((s,r)=>s+((r.nutritionPerStandardPortion as {kcal?:number}).kcal??0),0); return params.persons.filter(p=>params.isPresentAtMeal(p.id,params.mealType,params.dayIndex)).map((p)=>{ const target=estimateDailyCalories(p)*(params.isSportDay(p.id,params.dayIndex)?1.1:1)*params.mealDistribution[params.mealType]; const multiplier=Math.max(0.6,Math.min(1.6,target/Math.max(1,base))); return { personId:p.id, personName:p.name, multiplier:Number(multiplier.toFixed(2)), portionLabel:getPortionLabel(multiplier), estimatedCalories:Math.round(base*multiplier), macroTargets:estimateMacroTargets(p)};}); }
export function buildSimpleSuggestionPortions(params:{mealType:Extract<MealType,"breakfast"|"afternoon_snack">;persons:Person[];dayIndex:number;isPresentAtMeal:(personId:string, mealType:MealType, dayIndex:number)=>boolean;isSportDay:(personId:string, dayIndex:number)=>boolean;mealDistribution:Record<MealType,number>}) { const kcal=params.mealType==="breakfast"?320:190; return params.persons.filter(p=>params.isPresentAtMeal(p.id,params.mealType,params.dayIndex)).map((p)=>{ const target=estimateDailyCalories(p)*(params.isSportDay(p.id,params.dayIndex)?1.1:1)*params.mealDistribution[params.mealType]; const m=Math.max(0.6,Math.min(1.6,target/kcal)); return { personId:p.id, personName:p.name, multiplier:Number(m.toFixed(2)), portionLabel:getPortionLabel(m), estimatedCalories:Math.round(kcal*m), macroTargets:estimateMacroTargets(p)};}); }
